# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ReprojectSaltLake.py
# Created on: 2016-04-12 15:23:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
inshp = "INPUT"
outshp = "OUTPUT"

# Process: Project
arcpy.Project_management(inshp, outshp, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "GCS_North_American_1983_To_WGS84", "PROJCS['NAD_1983_StatePlane_Utah_Central_FIPS_4302_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',1640416.666666667],PARAMETER['False_Northing',6561666.666666666],PARAMETER['Central_Meridian',-111.5],PARAMETER['Standard_Parallel_1',39.01666666666667],PARAMETER['Standard_Parallel_2',40.65],PARAMETER['Latitude_Of_Origin',38.33333333333334],UNIT['Foot_US',0.3048006096012192]]", "NO_PRESERVE_SHAPE", "")

